"""Colours for the GTK frontend: the user's GTK 4 palette when there is one (`~/.config/gtk-4.0/gtk.css`, as
generated by DankMaterialShell, matugen, Gradience…), else a dark or light preset, with per-key overrides
from the config. Also decides light vs dark from the desktop's colour-scheme setting."""

import re
from dataclasses import dataclass, fields, replace
from pathlib import Path

from . import logs

log = logs.get("theme")

_DEFINE = re.compile(r"@define-color\s+([\w-]+)\s+([^;]+);")
_IMPORT = re.compile(r"""@import\s+url\(\s*["']?([^"')]+)["']?\s*\)""")


@dataclass(frozen=True)
class Palette:
    background: str
    text: str
    muted: str
    card: str
    card_border: str
    accent: str
    accent_text: str
    empty: str


DARK = Palette(
    background="rgba(19,19,19,0.95)",
    text="#e2e2e2",
    muted="#9a9a9a",
    card="#1f1f1f",
    card_border="#2c2c2c",
    accent="#ffb866",
    accent_text="#482900",
    empty="#0c0c0c",
)
LIGHT = Palette(
    background="rgba(250,249,246,0.96)",
    text="#1c1b1a",
    muted="#5f5e5c",
    card="#ffffff",
    card_border="#dcdad5",
    accent="#8a4f00",
    accent_text="#ffffff",
    empty="#ecebe7",
)


def gtk_css_path(config_home: Path) -> Path:
    return config_home / "gtk-4.0" / "gtk.css"


def define_colors(path: Path, depth: int = 0) -> dict[str, str]:
    """`@define-color name value;` pairs from a GTK CSS file, following relative @imports one level deep."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return {}
    colors: dict[str, str] = {}
    if depth < 2:
        for imported in _IMPORT.findall(text):
            colors.update(define_colors((path.parent / imported).resolve(), depth + 1))
    colors.update({name: value.strip() for name, value in _DEFINE.findall(text)})
    return colors


def from_gtk(colors: dict[str, str], base: Palette) -> Palette:
    """Map the libadwaita-style names onto our palette; anything missing keeps the preset value."""
    if "window_bg_color" not in colors or "accent_bg_color" not in colors:
        return base
    return replace(
        base,
        background=colors["window_bg_color"],
        text=colors.get("window_fg_color", base.text),
        card=colors.get("card_bg_color", base.card),
        accent=colors["accent_bg_color"],
        accent_text=colors.get("accent_fg_color", base.accent_text),
    )


def prefers_dark() -> bool:
    """The desktop's colour-scheme setting (org.gnome.desktop.interface, honoured by most Wayland shells)."""
    try:
        from gi.repository import Gio

        source = Gio.SettingsSchemaSource.get_default()
        if source is None or source.lookup("org.gnome.desktop.interface", True) is None:
            return True
        return "dark" in Gio.Settings.new("org.gnome.desktop.interface").get_string("color-scheme")
    except Exception as e:  # noqa: BLE001
        log.debug("colour scheme unavailable: %s", e)
        return True


def build(mode: str, overrides: dict[str, str], config_home: Path) -> Palette:
    """`mode`: auto (GTK palette if any, else preset by colour scheme), dark or light. Overrides win."""
    if mode == "light":
        palette = LIGHT
    elif mode == "dark":
        palette = DARK
    else:
        palette = from_gtk(define_colors(gtk_css_path(config_home)), DARK if prefers_dark() else LIGHT)
    known = {f.name for f in fields(Palette)}
    valid = {k: str(v) for k, v in overrides.items() if k in known}
    for key in overrides.keys() - known:
        log.warning("colors: unknown key %r", key)
    return replace(palette, **valid)


def css(p: Palette) -> bytes:
    return f"""
window {{ background: {p.background}; color: {p.text}; font-family: system-ui; font-size: 15px; }}
.title {{ font-size: 19px; font-weight: 700; color: {p.accent}; margin: 6px 0 2px 0; }}
.hint {{ color: {p.muted}; font-size: 13px; margin-bottom: 8px; }}
.card {{ background: {p.card}; border: 2px solid {p.card_border}; border-radius: 12px; padding: 8px; }}
.card:hover {{ border-color: alpha({p.accent}, 0.5); }}
.card.active {{ border-color: {p.accent}; background: mix({p.card}, {p.accent}, 0.12); }}
.card label.name {{ font-weight: 600; }}
.card label.detail {{ color: {p.muted}; font-size: 12px; }}
.card label.shortcut {{ color: {p.accent}; font-size: 12px; font-weight: 700; }}
.empty {{ background: {p.empty}; color: {p.muted}; border-radius: 6px; }}
.nothing {{ color: {p.muted}; font-size: 15px; margin: 24px; }}
scrolledwindow {{ background: transparent; }}
entry.filter {{ background: {p.card}; color: {p.text}; border: 1px solid {p.card_border}; border-radius: 8px;
  margin-bottom: 8px; }}
entry.filter:focus-within {{ border-color: {p.accent}; }}
button.cancel {{ background: {p.card}; color: {p.text}; border: 1px solid {p.card_border}; border-radius: 8px;
  padding: 6px 14px; }}
""".encode()
